name: release
on:
  push:
    branches: [mainline]
  pull_request:
  workflow_dispatch:
env:
  CARGO_INCREMENTAL: 0
permissions:
  contents: write

jobs:
  release:
    name: ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # MUSL Targets
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
          - os: ubuntu-latest
            target: arm-unknown-linux-musleabihf
          - os: ubuntu-latest
            target: armv7-unknown-linux-musleabihf
          - os: ubuntu-latest
            target: aarch64-unknown-linux-musl
          - os: ubuntu-latest
            target: i686-unknown-linux-musl

          # Android targets
          - os: ubuntu-latest
            target: aarch64-linux-android
          - os: ubuntu-latest
            target: armv7-linux-androideabi

          # Darwin targets
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: macos-latest
            target: aarch64-apple-darwin

          # Windows targets
          - os: windows-latest
            target: x86_64-pc-windows-msvc
          - os: windows-latest
            target: aarch64-pc-windows-msvc

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get version
        id: get_version
        uses: SebRollen/toml-action@v1.2.0
        with:
          file: Cargo.toml
          field: package.version

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Setup cache
        uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.target }}

      - name: Install build deps (macOS)
        if: runner.os == 'macOS'
        run: brew install protobuf

      - name: Install build deps (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler

      - name: Install zig
        if: runner.os == 'Linux' && !contains(matrix.target, 'android')
        uses: mlugg/setup-zig@v2

      - name: Install cargo-zigbuild
        if: runner.os == 'Linux' && !contains(matrix.target, 'android')
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-zigbuild

      - name: Install cargo-ndk
        if: contains(matrix.target, 'android')
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-ndk

      - name: Install Android NDK
        if: contains(matrix.target, 'android')
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r23
          local-cache: true

      - name: Install protoc (Windows)
        if: runner.os == 'Windows'
        uses: arduino/setup-protoc@v1
        with:
          version: "3.x"

      - name: Build binary (Linux)
        if: runner.os == 'Linux' && !contains(matrix.target, 'android')
        run: |
          cargo zigbuild --release --locked --target=${{ matrix.target }} --color=always --verbose

      - name: Build binary (Android)
        if: contains(matrix.target, 'android')
        run: |
          cargo ndk --target=${{ matrix.target }} build --release --locked --color=always --verbose

      - name: Build binary (macOS / Windows)
        if: runner.os == 'macOS' || runner.os == 'Windows'
        run: |
          cargo build --release --locked --target=${{ matrix.target }} --color=always --verbose

      - name: Package (*nix)
        if: runner.os != 'Windows'
        run: >
          tar -cv
          LICENSE README.md
          -C target/${{ matrix.target }}/release/ otadump
          | gzip --best
          > 'otadump-${{ steps.get_version.outputs.value }}-${{ matrix.target }}.tar.gz'
      - name: Package (Windows)
        if: runner.os == 'Windows'
        run: >
          7z a 'otadump-${{ steps.get_version.outputs.value }}-${{ matrix.target }}.zip'
          LICENSE README.md
          ./target/${{ matrix.target }}/release/otadump.exe
      - name: Upload artifact
        uses: actions/upload-artifact@v4.6.0
        with:
          name: ${{ matrix.target }}
          path: |
            *.deb
            *.tar.gz
            *.zip
      - name: Create release
        if: ${{ github.ref == 'refs/heads/mainline' && startsWith(github.event.head_commit.message, 'chore(release)') }}
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            *.deb
            *.tar.gz
            *.zip
          name: ${{ steps.get_version.outputs.value }}
          tag_name: ""
